{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.names.fullname" . }}-pv
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    "name": {{ include "common.names.fullname" . }}-pv
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- else }}
  - {{ .Values.persistence.accessMode | quote }}
  {{- end }}
  {{- if .Values.persistence.nfs.host }}
  nfs:
    readOnly: {{ .Values.persistence.nfs.readOnly }}
    server: {{ .Values.persistence.nfs.host }}
    path: {{ .Values.persistence.nfs.path }}
  {{- end }}
{{- end }}